### PR TITLE
add more verbose log for fs cleanup

### PR DESCRIPTION
**Pull request by svenwltr**
* added log output, which prints found directories
* handle errors correctly

### CODE REVIEW

**Comment by svenwltr** [comment]
@rebuy-de/prp-partial-deployment-cleanup

**Comment by hendrik-rebuy** [comment]
:+1:

**Comment by svenwltr** [comment]
@rebuy-de/prp-partial-deployment-cleanup I went the easy way and wrapped occurring errors in a `ExitCoder`, like the library wants it.

Nevertheless, for me the `github.com/codegangsta/cli` has disqualified itself by eating my errors :rage1: ... I am just to lazy to fix it by replacing.

**Comment by bjoernhaeuser** [comment]
You need to remove the binary from your commit :)

👍

**Pull request merged**
