### PR TITLE
improve hack scripts

### PR DESCRIPTION
**Pull request by svenwltr**
SCNR

* cleanup `hack/` scripts
* using `source` instead of execution other scripts, so we can share env vars

### CODE REVIEW

**Comment by svenwltr** [comment]
@rebuy-de/prp-partial-deployment-cleanup Please review

**Comment by bjoernhaeuser** [comment]
👍

**Comment by das-vinculum** [comment]
👍

**Comment by hendrik-rebuy** [comment]
:+1:

**Pull request merged**
